export default {
  PRODUCTS: "PRODUCTS",
  REFRESH_PRODUCTS: "REFRESH_CITIES",
  ADD_PRODUCT: "ADD_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  CITIES: "CITIES",
  REFRESH_CITIES: "REFRESH_CITIES",
  ADD_CITY: "ADD_CITY",
  DELETE_CITY: "DELETE_CITY",
  EDIT_CITY: "EDIT_CITY",
};
